apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: finflow
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'finflow-backend'
        static_configs:
          - targets: ['finflow-app-service:8080']
