# --- Etapa 1: Build de estáticos ---
# Usamos $BUILDPLATFORM para que npm install y npm run build corran nativamente en x86
FROM --platform=$BUILDPLATFORM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# --- Etapa 2: Servidor Nginx Final ---
# Nginx se descargará según la arquitectura de destino (amd64 o arm64)
FROM nginx:1.25-alpine

COPY --from=build /app/dist /usr/share/nginx/html

RUN echo 'server { \
    listen 3000; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html index.htm; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
