FROM node:20-alpine

WORKDIR /app

# Copia los archivos de configuración de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código del frontend
COPY . .

# Expone el puerto por defecto de Vite
EXPOSE 5173

# Arranca Vite asegurando que escuche peticiones externas al contenedor (--host)
CMD ["npm", "run", "dev", "--", "--host"]
