environment: "staging"

backend:
  replicas: 1
  port: 8080
  image:
    repository: josiastomasnanez/finflow-app
    tag: 722252a89ec352fe181fc84531b2723180b8f0ef
  databaseHost: "finflow-staging-postgres-service"
  databasePort: "5432"
  redisUrl: "redis://finflow-staging-redis-service:6339/0"
  unleashUrl: "http://unleash-web.finflow-infra.svc.cluster.local:4242/api"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {}
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    cooldownPeriod: 300
    threshold: 10

# --- SECCIÓN CORREGIDA PARA ENTORNO LOCAL (STAGING) ---
database:
  enabled: true       # Activamos la base de datos PostgreSQL de Staging
  storageSize: 1Gi    # Mantenemos tu tamaño asignado de 1Gi para pruebas

frontend:
  replicas: 1
  image:
    repository: josiastomasnanez/finflow-frontend
    tag: 722252a89ec352fe181fc84531b2723180b8f0ef
  apiUrl: "http://staging.finflow.local/api"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {}

ingress:
  enabled: true
  className: "traefik"
  host: "staging.finflow.local"
