# values-keda.yaml
resources:
  operator:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

prometheus:
  operator:
    enabled: false  
  metrics:
    podMonitor:
      enabled: true
      additionalLabels:
        release: finflow-infra-prometheus

rbac:
  customRules:
    - apiGroups: ["argoproj.io"]
      resources: ["rollouts", "rollouts/scale", "rollouts/status"]
      verbs: ["get", "list", "watch", "update", "patch"]

metricsServer:
  openshift: false
