backend:
  replicas: 1
  port: 8080
  image:
    repository: josiastomasnanez/finflow-app
    tag: v2
  databaseUrl: "postgresql://finflow_user:SuperPasswordSegura123@finflow-staging-postgres-service:5432/finflow_db?sslmode=disable"
  redisUrl: "redis://finflow-staging-redis-service:6339/0"
  unleashToken: "*:development.ab019863e72c308331b4cd4c2f0178670353e4e4b6e1d30b5a0ddc31"
  unleashUrl: "http://unleash-web.finflow-infra.svc.cluster.local:4242/api"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {}

database:
  user: finflow_user
  password: SuperPasswordSegura123
  name: finflow_db
  storageSize: 1Gi 

frontend:
  replicas: 1
  image:
    repository: josiastomasnanez/finflow-frontend
    tag: v3
  apiUrl: "http://staging.54.214.12.34.nip.io/api"  
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {} 

ingress:
  host: "staging.54.214.12.34.nip.io"
  unleashHost: "unleash-staging.54.214.12.34.nip.io"
  enabled: true
