environment: "staging"
networkPolicy:
  enabled: true
backend:
  replicas: 1
  port: 8080
  image:
    repository: harbor.finflow.local/finflow/finflow-backend
    tag: 0c479d55e549ca387ea26e6fd633176e3c941c17
  databaseHost: "finflow-staging-postgres-service"
  databasePort: "5432"
  redisUrl: "redis://finflow-staging-redis-service:6339/0"
  unleashUrl: "http://unleash-web.finflow-infra.svc.cluster.local:4242/api"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {}
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    cooldownPeriod: 300
    threshold: 10
database:
  enabled: true
  storageSize: 1Gi
frontend:
  replicas: 1
  image:
    repository: harbor.finflow.local/finflow/finflow-frontend
    tag: 0c479d55e549ca387ea26e6fd633176e3c941c17
  apiUrl: "http://staging.finflow.local/api"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {}
ingress:
  enabled: true
  className: "traefik"
  host: "staging.finflow.local"
