argo-rollouts:
  installCRDs: false

backend:
  replicas: 3
  port: 8080
  image:
    repository: josiastomasnanez/finflow-app
    tag: v2
  databaseUrl: "postgresql://finflow_prod_user:ContrasenaMegaUltraSegura456@finflow-prod-postgres-service:5432/finflow_prod_db?sslmode=disable"
  redisUrl: "redis://finflow-prod-redis-service:6339/0"
  unleashToken: "*:production.55d7d23c5ec80c0c6c061422bcc899320d06dc077523ab62027580c9"
  unleashUrl: "http://unleash-web.finflow-infra.svc.cluster.local:4242/api"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {}

database:
  user: finflow_prod_user
  password: ContrasenaMegaUltraSegura456
  name: finflow_prod_db
  storageSize: 5Gi 

frontend:
  replicas: 3
  image:
    repository: josiastomasnanez/finflow-frontend
    tag: v3
  apiUrl: "http://prod.finflow.local/api"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {}

ingress:
  enabled: true
  className: "traefik" # <-- AGREGADO para tu clúster local
  host: "prod.finflow.local"
