argo-rollouts:
  installCRDs: false

environment: "prod" 

backend:
  replicas: 3
  port: 8080
  image:
    repository: josiastomasnanez/finflow-app
    tag: v2
  databaseHost: "finflow-prod-postgres-service"
  databasePort: "5432"
  redisUrl: "redis://finflow-prod-redis-service:6339/0"
  unleashUrl: "http://unleash-web.finflow-infra.svc.cluster.local:4242/api"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {}

database:
  storageSize: 5Gi 

frontend:
  replicas: 3
  image:
    repository: josiastomasnanez/finflow-frontend
    tag: v3
  apiUrl: "http://prod.finflow.local/api"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {}

ingress:
  enabled: true
  className: "traefik"
  host: "prod.finflow.local"
