environment: "staging" 

backend:
  replicas: 1
  port: 8080
  image:
    repository: josiastomasnanez/finflow-app
    tag: v2
  databaseHost: "finflow-staging-postgres-service"
  databasePort: "5432"
  redisUrl: "redis://finflow-staging-redis-service:6339/0"
  unleashUrl: "http://unleash-web.finflow-infra.svc.cluster.local:4242/api"
  argoStrategy:
    steps:
      - setWeight: 33
        pause: {}
  # 🔥 LA SOLUCIÓN AL INCENDIO:
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    cooldownPeriod: 300
    threshold: 10

database:
  storageSize: 1Gi 

frontend:
  replicas: 1
  image:
    repository: josiastomasnanez/finflow-frontend
    tag: v3
  apiUrl: "http://k8s-finflowstaginggro-2d1f40137d-1302572390.us-east-1.elb.amazonaws.com/api"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {} 

ingress:
  enabled: true
  className: "alb"
  host: "k8s-finflowstaginggro-2d1f40137d-1302572390.us-east-1.elb.amazonaws.com"
  annotations:
    alb.ingress.kubernetes.io/group.name: finflow-staging-group
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
