environment: "staging"
networkPolicy:
  enabled: true
backend:
  replicas: 1
  port: 8080
  image:
    repository: harbor.finflow.local/finflow/finflow-backend
    tag: 686adc5e670f8eb8a81dfcd618978a60930d45f7
  databaseHost: "finflow-staging-postgres-service"
  databasePort: "5432"
  redisUrl: "redis://finflow-staging-redis-service:6339/0"
  unleashUrl: "http://unleash-web.finflow-infra.svc.cluster.local:4242/api"
  otelExporterOtlpEndpoint: "finflow-infra-jaeger.finflow-infra.svc.cluster.local:4317"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {}
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    cooldownPeriod: 300
    threshold: 10
database:
  enabled: true
  storageSize: 1Gi
frontend:
  replicas: 1
  image:
    repository: harbor.finflow.local/finflow/finflow-frontend
    tag: 686adc5e670f8eb8a81dfcd618978a60930d45f7
  apiUrl: "http://staging.finflow.local/api"
  argoStrategy:
    steps:
      - setWeight: 33
      - pause: {}
ingress:
  enabled: true
  className: "traefik"
  host: "staging.finflow.local"
