apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-self-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/josiastomasnanez/FinFlow.git'
    targetRevision: main
    path: argocd-infrastructure/argocd-config
    directory:
      include: 'argocd-cm-patch.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
