apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finflow-infra
  namespace: argocd
spec:
  project: default
  sources:
    # 1. Apuntamos a la carpeta vacía/limpia 'argocd-infrastructure/argocd-config'
    # Así ArgoCD no se choca con ningún JSON de la raíz.
    - repoURL: 'https://github.com/josiastomasnanez/FinFlow.git'
      targetRevision: main
      path: argocd-infrastructure/argocd-config
      ref: root
    # 2. El Source del Chart de Infraestructura
    - repoURL: 'https://github.com/josiastomasnanez/FinFlow.git'
      targetRevision: main
      path: finflow-infra
      helm:
        valueFiles:
          # Subimos un nivel relativo desde 'argocd-config' para alcanzar la raíz original
          - $root/../values-infra.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: finflow-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
