apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finflow-staging
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/josiastomasnanez/FinFlow.git'
      targetRevision: main
      ref: root
    - repoURL: 'https://github.com/josiastomasnanez/FinFlow.git'
      targetRevision: main
      path: finflow-chart
      helm:
        valueFiles:
          - $root/values-staging.yaml 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: finflow-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      name: finflow-staging-app 
      jsonPointers:
        - /spec/replicas
