apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
    chart: opentelemetry-collector
    targetRevision: 0.172.1
    helm:
      values: |
        image:
          repository: "otel/opentelemetry-collector-contrib"
        mode: daemonset
        config:
          exporters:
            otlp/jaeger:
              endpoint: "jaeger.opentelemetry.svc.cluster.local:4317"
              tls:
                insecure: true
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [debug, otlp/jaeger]
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: opentelemetry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
