apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otelcol-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
    chart: opentelemetry-collector
    targetRevision: '0.173.1'
    helm:
      values: |
        mode: daemonset
        image:
          repository: otel/opentelemetry-collector-contrib

        presets:
          logsCollection:
            enabled: true

        ports:
          otlp:
            enabled: false
          otlp-http:
            enabled: false
          jaeger-compact:
            enabled: false
          jaeger-thrift:
            enabled: false
          jaeger-grpc:
            enabled: false
          zipkin:
            enabled: false
          metrics:
            enabled: false

        config:
          receivers:
            otlp: null
            jaeger: null
            zipkin: null
            prometheus: null
          exporters:
            debug: null
            otlphttp/loki:
              endpoint: http://loki.finflow-infra.svc.cluster.local:3100/otlp
              tls:
                insecure: true
          service:
            pipelines:
              traces: null
              metrics: null
              logs:
                exporters: [otlphttp/loki]
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: finflow-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
