apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finflow-infra
  namespace: argocd
spec:
  project: default
  sources:
    # 1. Mapeamos la raíz pero le indicamos a ArgoCD que SOLO procese este archivo
    - repoURL: 'https://github.com/josiastomasnanez/FinFlow.git'
      targetRevision: main
      path: .
      ref: root
      directory:
        include: 'values-infra.yaml' # 👈 Crucial: Así ignora por completo el iam_policy.json
    # 2. El Chart de Infraestructura que consume el value mapeado arriba
    - repoURL: 'https://github.com/josiastomasnanez/FinFlow.git'
      targetRevision: main
      path: finflow-infra
      helm:
        valueFiles:
          - $root/values-infra.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: finflow-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
