---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-pull-secret
  namespace: finflow-staging
spec:
  encryptedData:
    .dockerconfigjson: AgAa/sJb0y8OyYWny18gJ2VXvFwl2yALyJYYrLTx+moML2ljsWE3+q+8KDOocfFeXCJJrwZJVWmFQWgao+Grcs/56HSpIkJKKAZ6fCs9Pi0kkysSCisbm7Cw3lOtUBo6qy+FhT1NZ/n51H9or5NWdPECCnmf+9rWh5pVTjyikUsCs9CG1uV/nPSV6pp5jM1R8FP2K5ZLhRdW5wWK0xDd8hjE42J1oRc/WzYIDprcUrA6sYwGORF41bEmKprIxYow1qxI8yPYsxICeNi6Nbbu8V/SiKDPlqjLsPJ2dS4mtisNfw0bQYO6BUX8pE+nmlapF0kLntNgzwFml4L0d3BywMn4Uhu4KqTp/irZtso31+cbkSRlFKNtOgtvnOeHp7zRzhTDdYLt0JU3KAaQrriQLHfFBI8M7cEPvrKKN9UtTG1M09EMCITL/GqKexVzVHK13rNldLVoXMV8wV4jjjiFU4JRTwv4LTsp4Ig9MKy3bzml1TO5REC44+6Km6Li4IBSOTvsW8ySb5S48t8mxujhVLX3QxZUKXunAAV+EVcb/ZGH6LhWMbQuwXSWD5oLIfq+WVGOJRWXed7nUJAFaKefxsJPRUu6PjstJFyCRQe8rxYOq6hgFkQ4m1qFFLY6qcsZmh0f85cNWrAwaO0RPl3Rv4fI9msyY/dPUDdGg0lcL/XYDGF4zqWPh0opHB24IfT83P9DyfaXOmqHorU1uE052eLZ2Bcerrz4S739Xq4yg6+k5c02QhK3ota/+BWPA0HTOsDUCKlCZeDnjdvlrcSpxaeiApBvrtTFmT5Sk1OZplR0xixlK6mGS0YfAhnkEC781HZgzWY4aLH9Rv0fuuHDJ4Wj77Uz0rk5LSJmfwqCd19gHZtcn1mg+qJ3e0veWZ5Tc0kdyyFyBK2P56Doe7ZNIyEqlDVv7v2q8a/bo1KS6HUwHZ1YX+KzTGOq95YTsvuSyfRtSr+G1TI=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-pull-secret
      namespace: finflow-staging
    type: kubernetes.io/dockerconfigjson
