---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-pull-secret
  namespace: finflow-prod
spec:
  encryptedData:
    .dockerconfigjson: AgCO+z02ZALil6DBXg+AUfnakPU8lkSq5Eb7qdxo/eG4TvSm/y8xgEh2DuGbcoTpZHXs93lJkpceDWU4JUGml9CnRAahE3cgXr1RrNmUv3d93Litulg0/KmqiiFQCPa6G+CEf1JT9VG6YtTdEoOyC9XQ10A9s01cniCanMEnMvyAM9FBF9GCwSsNhQ6mIgpFkMG9Lhv2ZJfPivz+6zj3t5x9pu+Qb468J7bNBM3LDn8fEP3LO9XiDq1LXFWx1oGX9BZGq24d8rV21Fii/BD7/vFNJ3fSBh0CviehR/RYrW46PCVH9E10u9bNvD2OQl10b3To0SH42RV6WYCxKwsyM0J+MTQ+ewvwXcUbC/BMfg/qGiHexYZWX+o8KgXgASJ2CmRMZFyP+I4G2zCth3wvZ1yVElVBUEWgfROCGN9mwgM3Ugk3WzoCUsndS9xc0+Y5jW7gmud0GWf4dPhVT28d+79b5g7PvcbfB0e8hABmMlAyG3VpmGI+WC0KA7kglCxAHrTK7SNgn50ofPJDZOZlcTuwz90VtbODoBlQNaWsAIH+DmbECfu2WTfQz4F+USwhqqR2OK9FfRKKOZY0JJYbW9pmTFxJQqRDGGoWmO9yfBGDIhUjmTykwiZCPDiet+qES/NyguNmvmXlbuM+Xw9L+RbukwwNWIP+A5hF2oDD+Z8GTv17jUbB2m4cgI7K2kr0qb9RId/39UzozTa/gSKHcB/rmoD++ojkg9pW1sIhc0VSWWekO/CYYuFtZj/Aho78HX1FT1xcDDGNm9HXPbEfO/7we4t35l4hTtMm0eS3Q2Kg79lidy76G0DA8uUaKZeWtGhDci2rTRgqXvbg97a1o7oajIzF7GjnQI5KHCD9Qroscn+hGe8qZf+ZtLKAZUpEQbeO0FPOXVPJjNe5jDb7U/cywir42nsxmT/4tZjGusxPWjo4vKqC4WjD0cngCYOb6enXwNmMTzY=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-pull-secret
      namespace: finflow-prod
    type: kubernetes.io/dockerconfigjson
