apiVersion: v1
kind: Secret
metadata:
  name: finflow-backend-secret
  namespace: finflow
type: Opaque
stringData: 
  UNLEASH_TOKEN: "*:development.61bf87c01b5869d523ae5985e6bd6e2292284998f88dd4da1934df7b"
