apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finflow-infra
  namespace: argocd
spec:
  project: default
  sources:                           # <-- Cambiamos 'source' por 'sources' (en plural)
    - repoURL: 'https://github.com/josiastomasnanez/FinFlow.git'
      targetRevision: main
      ref: root                      # <-- Le ponemos un alias a la raíz del proyecto
    - repoURL: 'https://github.com/josiastomasnanez/FinFlow.git'
      targetRevision: main
      path: finflow-chart            # <-- La carpeta del chart principal
      helm:
        valueFiles:
          - $root/values-infra.yaml  # <-- Usamos el alias para buscar el archivo en la raíz real
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: finflow-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
