apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finflow-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/josiastomasnanez/FinFlow.git'
    targetRevision: main
    path: finflow-chart
    helm:
      valueFiles:
        - ../values-staging-aws.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: finflow-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
