apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kedacore.github.io/charts'
    chart: keda
    targetRevision: 2.14.0 
    helm:
      valuesObject:
        # 🚀 CAMBIAMOS ESTO A FALSE PARA QUE NO INSTALE EL AUTOSCALER POR DEFECTO:
        prometheus:
          operator:
            enabled: false
        rbac:
          customRules:
            - apiGroups: ["argoproj.io"]
              resources: ["rollouts", "rollouts/scale", "rollouts/status"]
              verbs: ["get", "list", "watch", "update", "patch"]
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: finflow-infra 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
