apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-aws
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/josiastomasnanez/FinFlow.git'
    targetRevision: main
    path: argocd-infrastructure/apps-aws
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
