{{- if .Values.prometheus }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-prometheus-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-prometheus-cluster-role
rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-prometheus-crb
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-prometheus-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-prometheus-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-prometheus-config
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'finflow-backend-multipod'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                {{- range .Values.prometheus.monitoredNamespaces }}
                - {{ . }}
                {{- end }}
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: .*-app-service
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "8080"
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      - job_name: 'keda-operator'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - {{ .Release.Namespace }} # finflow-infra
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: keda-operator  # El servicio base generado por el chart de KEDA
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "8080"
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - action: replace
            target_label: job
            replacement: keda-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-prometheus
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-prometheus
    spec:
      serviceAccountName: {{ .Release.Name }}-prometheus-sa
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-grafana-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana
    spec:
      securityContext:      
        fsGroup: 472        
      containers:
        - name: grafana
          image: grafana/grafana-oss:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-grafana-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
{{- end }}
