{{- if .Values.prometheus }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-prometheus
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/prometheus-config.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}-prometheus
    spec:
      serviceAccountName: {{ .Release.Name }}-prometheus-sa
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-service
spec:
  selector:
    app: {{ .Release.Name }}-prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana
    spec:
      securityContext:      
        fsGroup: 472        
      containers:
        - name: grafana
          image: grafana/grafana-oss:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards
              mountPath: /var/lib/grafana-dashboards
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-grafana-pvc
        - name: grafana-datasources
          configMap:
            name: {{ .Release.Name }}-grafana-datasources
        - name: grafana-dashboards-provider
          configMap:
            name: {{ .Release.Name }}-grafana-dashboards-provider
        - name: grafana-dashboards
          projected:
            sources:
              - configMap:
                  name: {{ .Release.Name }}-grafana-dashboard-golden-signals
              - configMap:
                  name: {{ .Release.Name }}-grafana-dashboard-loki
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana-service
spec:
  selector:
    app: {{ .Release.Name }}-grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
{{- end }}
