{{- if .Values.unleash }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-unleash-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.unleash.db.storageSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-unleash-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-unleash-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-unleash-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA                        
              value: /var/lib/postgresql/data/pgdata        
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-unleash-secret
                  key: UNLEASH_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-unleash-secret
                  key: UNLEASH_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-unleash-secret
                  key: UNLEASH_DB_PASSWORD
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-unleash-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-unleash-db
spec:
  selector:
    app: {{ .Release.Name }}-unleash-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-unleash-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-unleash-web
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-unleash-web
    spec:
      containers:
        - name: unleash-web
          image: unleashorg/unleash-server:latest
          ports:
            - containerPort: 4242
          env:
            - name: DATABASE_HOST
              value: "{{ .Release.Name }}-unleash-db" 
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-unleash-secret
                  key: UNLEASH_DB_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-unleash-secret
                  key: UNLEASH_DB_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-unleash-secret
                  key: UNLEASH_DB_PASSWORD
            - name: DATABASE_SSL
              value: "false"
            - name: BYPASS_WWW_AUTH_FOR_TESTING
              value: "true"
            - name: INIT_ADMIN_API_TOKENS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-unleash-secret
                  key: UNLEASH_ADMIN_TOKEN
            - name: INIT_CLIENT_API_TOKENS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-unleash-secret
                  key: INIT_CLIENT_API_TOKENS
            - name: INIT_FEATURES
              value: '[{"name":"login-feature-flag","description":"Controla el acceso al nuevo modulo de login","type":"release","enabled":true,"stale":false}]'
---
apiVersion: v1
kind: Service
metadata:
  name: unleash-web
spec:
  selector:
    app: {{ .Release.Name }}-unleash-web
  ports:
    - port: 4242
      targetPort: 4242
  type: ClusterIP
{{- end }}
