apiVersion: apps/v1
kind: Deployment
metadata:
  name: finflow-frontend
  namespace: finflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finflow-frontend
  template:
    metadata:
      labels:
        app: finflow-frontend
    spec:
      containers:
        - name: finflow-frontend
          image: finflow-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: VITE_API_URL
              value: "http://localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: finflow-frontend
  namespace: finflow
spec:
  selector:
    app: finflow-frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
