server {
    listen 80;
    server_name localhost;

    # ⚡ EVITA EL CRASH EN ARRANQUE: Resuelve las IPs de Docker dinámicamente.
    resolver 127.0.0.11 valid=5s;

    # AUTENTICACIÓN DE UNLEASH
    location /auth/ {
        proxy_pass http://unleash-web:4242;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # API ADMIN DE UNLEASH
    location /api/admin/ {
        proxy_pass http://unleash-web:4242;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # API FRONTEND DE UNLEASH 
    location /api/frontend/ {
        proxy_pass http://unleash-web:4242;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # API FINFLOW (Backend Go)
    location /api/ {
        # Usamos variable para que Nginx no valide el host al iniciar
        set $backend_upstream http://finflow-app:8080; 
        
        proxy_pass $backend_upstream; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # STATIC DE UNLEASH
    location /static/ {
        proxy_pass http://unleash-web:4242/static/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Unleash 
    location /unleash/ {
        proxy_pass http://unleash-web:4242;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # MÉTRICAS DE PROMETHEUS SERVER
    location /metrics/ {
        proxy_pass http://prometheus:9090/metrics;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 💻 FRONTEND (Modo Producción / K8s Ready)
    location / {
        # Usamos variable y apuntamos al puerto 3000 de tu Nginx interno
        set $frontend_upstream http://finflow-frontend:3000;
        
        proxy_pass $frontend_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # MONITOREO CON GRAFANA
    location /grafana/ {
        proxy_pass http://grafana:3000; # Sin barra al final, Grafana maneja su subpath nativo
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
