apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: {{ .Release.Namespace }}
  {{- if .Values.ingress.controllerRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.ingress.controllerRoleArn }}"
  {{- end }}
