{{- if and .Values.ingress .Values.ingress.enabled .Values.ingress.controllerRoleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.ingress.controllerRoleArn }}"
{{- end }}
