{{- if .Values.backend }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config 
data:
  UNLEASH_URL: "{{ .Values.backend.unleashUrl }}"
  UNLEASH_APP_NAME: "finflow-app"
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.backend.replicas }} 
  strategy:
    canary:
      steps:
        {{- toYaml .Values.backend.argoStrategy.steps | nindent 8 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: finflow-app
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}" 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app-secret
                  key: DB_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app-secret
                  key: DB_PASSWORD
            # 1. Inyectamos de forma segura el DB_NAME desde el secreto
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app-secret
                  key: DB_NAME
            # 2. Modificamos la URL para que use el fragmento inyectado $(DATABASE_NAME) sin romper Helm
            - name: DATABASE_URL
              value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@{{ .Values.backend.databaseHost }}:{{ .Values.backend.databasePort }}/$(DATABASE_NAME)?sslmode=disable"
            
              - name: REDIS_URL
              value: "{{ .Values.backend.redisUrl }}"
            - name: UNLEASH_URL
              value: "{{ .Values.backend.unleashUrl }}"
            - name: UNLEASH_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-backend-config
                  key: UNLEASH_APP_NAME
            - name: UNLEASH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-app-secret
                  key: UNLEASH_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP
{{- end }}
