{{- if .Values.database }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
type: Opaque
stringData:
  postgres-user: "{{ .Values.database.user }}"
  postgres-password: "{{ .Values.database.password }}"
  postgres-db: "{{ .Values.database.name }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storageSize }} 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres-db
    spec: 
      containers:
        - name: postgres 
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: postgres-db
          nodeSelector:
            tipo: BD 
          tolerations:
            - key: "tipo"
              operator: "Equal"
              value: "BD"
              effect: "NoSchedule" 
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
spec:
  selector:
    app: {{ .Release.Name }}-postgres-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
{{- end }}
