{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  ingressClassName: traefik 
  rules:
    # 1. Frontend y Backend
    - host: "{{ .Values.ingress.host | default "finflow.local" }}" 
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-app-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend-service
                port:
                  number: 3000

    # 2. Unleash
    - host: "{{ .Values.ingress.unleashHost | default "unleash.finflow.local" }}" 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                {{- if eq .Release.Name "finflow-staging" }}
                name: unleash-web
                {{- else }}
                name: unleash-central-bridge-service
                {{- end }}
                port:
                  number: 4242

    # 3. Grafana
    - host: "{{ .Values.ingress.grafanaHost | default "grafana.finflow.local" }}" 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-grafana-service
                port:
                  number: 3000
{{- end }}
