apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-backend-autoscaler
  namespace: {{ .Release.Namespace }} 
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ .Release.Name }}-app 
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 300
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://finflow-infra-prometheus.finflow-infra.svc.cluster.local:9090
      metricName: http_requests_total
      query: sum(rate(http_requests_total{app="{{ .Release.Name }}-app"}[2m]))
      threshold: '15'
