{{- if .Values.backend }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-backend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ .Release.Name }}-app
    envSourceContainerName: finflow-app
  minReplicaCount: {{ .Values.backend.autoscaling.minReplicas | default 1 }}
  maxReplicaCount: {{ .Values.backend.autoscaling.maxReplicas | default 5 }}
  cooldownPeriod: {{ .Values.backend.autoscaling.cooldownPeriod | default 300 }}
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://finflow-infra-prometheus-service.finflow-infra.svc.cluster.local:9090
      metricName: gin_requests_total
      query: sum(rate(gin_requests_total{pod=~"{{ .Release.Name }}-app-.*"}[2m]))
      threshold: '{{ .Values.backend.autoscaling.threshold | default 15 }}'
{{- end }}
