name: CD - Deploy to Production

on:
  release:
    types: [published] # El trigger: se activa SOLO cuando publicás una Release en GitHub

jobs:
  deploy-prod:
    name: Deploy Backend & Frontend to Production
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Production (Backend)
        run: |
          curl -X POST "${{ secrets.RENDER_PROD_DEPLOY_HOOK }}"

      - name: Trigger Vercel Production (Frontend)
        run: |
          curl -X POST "${{ secrets.VERCEL_PROD_DEPLOY_HOOK }}"
